CC = gcc
CFLAGS = -Wall -g
OBJS = hw2.o
EXECS = hw2

build : hw2
	./hw2 projects

%.o : %.c
	$(CC) $(CFLAGS) -c -o $@ $^

hw2 : $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^

debug :	hw2
	gdb ./hw2 -tui

clean : 
	rm *.o $(EXECS)
Footer